### ISSUE TITLE
Can't claim reward 2.1.7

### ISSUE THREAD

**Issue by killerjerick** [Pixelmon-Development/BetterDexRewards#22]
Having a bit of an issue on a server I'm running with a few friends, we've got Spongeforge 2838-7.4.2 I've set up the SQL and have 2 other mods working fine (WT and Bingo) however for some reason, we can't claim the dex completion rewards, /dexr just brings up the [interface](https://i.imgur.com/sL8dR1z.png), even though we're being [pestered by the mod that we have a reward level we can claim](https://i.imgur.com/n8nE46N.png). Is this just me being stupid and not understanding how to claim the reward? 

Many thanks

**Comment by prodigyrick** [comment]
same
