### ISSUE TITLE
[1.16.5-3.0.1] Missing Pokémon UI displayed in the incorrect order

### ISSUE THREAD

**Issue by HackuJacku** [Pixelmon-Development/BetterDexRewards#26]
In the Missing Pokémon UI, the UI Elements of Pokémon required to be caught are displayed in the incorrect order. For example: 791, 659, 660, 263, 529, etc.

**Comment by austin4195** [comment]
Not sure if this is also along the same lines but the UI elements of the pokemon are not displaying correctly. It looks as if they are zoomed in

**Comment by danorris709** [comment]
> Not sure if this is also along the same lines but the UI elements of the pokemon are not displaying correctly. It looks as if they are zoomed in

This is a Pixelmon bug

**Comment by danorris709** [comment]
> In the Missing Pokémon UI, the UI Elements of Pokémon required to be caught are displayed in the incorrect order. For example: 791, 659, 660, 263, 529, etc.

Fixed for next version
