### ISSUE TITLE
Server crash on /hunts 

### ISSUE THREAD

**Issue by Rasgnarok** [Pixelmon-Development/BetterDexRewards#34]
https://gist.githubusercontent.com/Rasgnarok/b4131d73dd74b635cae6f81d02df02ef/raw/daca9101291c301e57b018fbb485458061c775f2/gistfile1.txt

Doesn't happen to all players, seems to be a selective few. Can't reproduce

**Comment by danorris709** [comment]
Fixed a while back :)
