### ISSUE TITLE
[Suggestion] - Check for Updated OT

### ISSUE THREAD

**Issue by FLalejandro** [Pixelmon-Development/BetterDexRewards#39]
In regards to the Original-Trainer-Only setting, I'd love to see this plugin have a command or a way to check if a Pokemon had its OT updated by something like /pokeedit.

Ex: 
[EXISTS] Player 1 is the OT of a Rillaboom
[EXISTS] Player 1 gives Player 2 the Rillaboom
[EXISTS] Player 2 uses /pokeedit which changes Rillaboom's OT to Player 2 instead of Player 1
[RESULT] Due to updated Original Trainer, Rillaboom now shows up in Player 2's PokeDex

Currently, if an OT is updated via /pokeedit, it won't register in the PokeDex of Player 2

**Comment by danorris709** [comment]
This is something that isn't stored by Pixelmon and so not something that this mod can really tell you. If the OT is changed then it's permanently changed and nothing can be done about that from an API perspective
