### ISSUE TITLE
close-on-click/commands-executed Not working

### ISSUE THREAD

**Issue by FamiliarAsh** [Pixelmon-Development/BetterDexRewards#41]
I tried asking for help in the Discord server and they told me that is was probably a bug, so I just wanted to report it here.

![image](https://user-images.githubusercontent.com/129208373/234914990-9e332fc5-d650-4b78-8df4-918312d27192.png)

**Comment by danorris709** [comment]
These commands are not implemented for any items in BetterDexRewards
