### ISSUE TITLE
Some kind of a logger error 

### ISSUE THREAD

**Issue by Yorick-06** [Pixelmon-Development/BetterDexRewards#44]
https://pastebin.com/raw/VeAWmSGB

**Comment by danorris709** [comment]
Looks like your database is not correctly setup in your config causing the player data to fail to load. If you would like additional support I recommend reading the [wiki](https://www.envyware.co.uk), and if you cannot find what you're looking for from there then joining the Discord.

**Comment by Yorick-06** [comment]
the configuration is basically default https://pastebin.com/UXeRsN7A
