### ISSUE TITLE
BetterDexRewards Mod Loading Error

### ISSUE THREAD

**Issue by Liarc** [Pixelmon-Development/BetterDexRewards#46]
Minecraft Crash Report - BetterDexRewards Mod Loading Error

Minecraft Version: 1.16.5
Forge Version: 36.2.34
Mod Name: BetterDexRewards
Mod Version: 3.2.4
Java Version: 1.8.0_51, Oracle Corporation
Pixelmon Version: 9.1.11

Description:
A mod loading error has occurred due to an unsupported class version in the BetterDexRewards mod.

Error Details: 
`java.lang.UnsupportedClassVersionError: com/envyful/better/dex/rewards/shade/envy/api/gui/factory/PlatformGuiFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by danorris709** [comment]
You need to update to Java 11
